### ISSUE TITLE
I can't get the player torches to light up

### ISSUE THREAD

**Issue by Bogus73** [RealDeuce/torch#13]
Hi. I would love to use this module but for some of my players the torch just doesn't work. When they right klick their token the symbol is there but it is crossed out and they can't activate it. 
I can do that as a dm without a problem though.

**Comment by jjspace** [comment]
The characters need to have a torch in their inventory to consume. I encountered that problem too. It would probably make sense to add a setting to globally change if players need to consume a torch to turn it on.

**Comment by RealDeuce** [comment]
Yes, players need a torch to light a torch... this is by design.
