### ISSUE TITLE
Dancing lights need vision

### ISSUE THREAD

**Issue by Strigoil** [RealDeuce/torch#4]
When you spawn dancing lights they do not have vision at the moment, which means when the player goes to move them it gets rather dark and difficult, can set manually for now but would appreciate a change.

**Comment by RealDeuce** [comment]
I debated that one quite a bit... the issue is that when they have vision, they allow the player to see things their token actually can't (ie: peek around corners).  I believe you can press ESC when moving the token to fall back to your token vision.

**Comment by RealDeuce** [comment]
Possibly a setting to control dancing light vision?  Would that do what you want?

**Comment by Strigoil** [comment]
Making it optional like that would work wonderful! Appreciate you giving this thought and consideration.

**Comment by CarnivorousM** [comment]
I have also noted that the Dancing lights that spawn have a 10 bright and 20 dim.
The spell reads that they merely have 10 dim.

**Comment by RealDeuce** [comment]
Done and Dancing Lights fixed.  Not tested yet though.
