### ISSUE TITLE
I'm not seeing the quantity of torches being updated on torch usage.

### ISSUE THREAD

**Issue by tposney** [RealDeuce/torch#6]
I looked at the code and (from my limited understanding) the existing code
```
// Now, remove a torch from inventory...
actor.data.items[torch].data.quantity -= 1;
 await actor.updateOwnedItem(actor.data.items[torch]);
```
updates the in memory copy of the item, then when it does the update owned item the quantity has already changed and the update is not committed to the db.
If I replace both lines with
```
await actor.updateOwnedItem({"_id": actor.data.items[torch]._id, "data.quantity": actor.data.items[torch].data.quantity - 1})
```
it seems to update the quantity correctly. I must be missing something, but tried turning off all modules and the same behaviour persists.

**Comment by RealDeuce** [comment]
Thanks, included in the next release.
